### GET request to example server

@userId = aoeuaoeuaa
@activityId = {{$random.uuid}}

POST http://localhost:5185/activities
Content-Type: application/json

{
    "userId": "{{userId}}",
    "activity": 
    {
        "id": "{{activityId}}",
        "name": "Activity 1",
        "type": "news",
        "data": {
            "id": "123",
            "title": "News Title"
        }
    }
}

###